services:
  - type: web
    name: facilito-emails
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: IMAGE_BASE_URL
        sync: false
      - key: UNSUBSCRIBE_URL
        sync: false
